### ISSUE TITLE
길 리스트중 이미지 있는경우 공백뜨는 이슈

### ISSUE THREAD

**Issue by namsoo5** [mash-up-kr/HikingClub_iOS#109]
## 문제사항
길목록 리스트를 볼 때 이미지있는경우 표시안됨
다시한번 카테고리를 클릭하면 보여짐

이미지 캐싱이 되어있으면 뜨고 안되어있으면 안뜨는 것 같음
시점확인하고 셀 업데이트하면 해결 할 수 있지않을까 가정

**Comment by dvHuni** [comment]
+ 셀 업데이트 시 이미지가 펼쳐지는 듯 한 애니메이션이 있음.

해당 상황 개선 필요해보임.
