### ISSUE TITLE
홈화면 UI 작업 마무리하기

### ISSUE THREAD

**Issue by dvHuni** [mash-up-kr/HikingClub_iOS#18]
## 문제사항
1차 해커톤때 미완성으로 만들어두었던 홈 화면 UI 마무리 
## 해야할 기능
- [x] 헤더 셀 UI
- [x] 리스트 셀 UI
## 스크린샷
<image src="https://user-images.githubusercontent.com/39300449/136400986-b4dafe3c-20f1-409f-9554-fa4fe01b70b6.png" width="375" height="812"/>

## 레퍼런스
[Figma](https://www.figma.com/file/NgL6IwfKsn1B5LJEVchJBh/Mash-Up-산악회-11기?node-id=164%3A9497)

**Comment by kor-Chipmunk** [comment]
오호.. 길 등록하는 부분만 웹부분 인걸까용

**Comment by dvHuni** [comment]
> 오호.. 길 등록하는 부분만 웹부분 인걸까용

넵 !! 길 등록 및 길 상세 페이지는 웹뷰로 진행할 예정입니다! 😄

**Comment by dvHuni** [comment]
@namsoo5 헤더 셀 작업은 언제 예정??

**Comment by namsoo5** [comment]
@dvHuni  컴포넌트만들어둬서 이제 뚝딱 작업가능함~
