### ISSUE TITLE
탭바 사라지지 않는 현상

### ISSUE THREAD

**Issue by dvHuni** [mash-up-kr/HikingClub_iOS#20]
## 문제사항
화면 push 시 탭바가 사라지지 않는 현상
## 해결방법 
.. 잘모르겠음
여러가지 시도해 보아야 할듯
## 해야할 기능
- [ ] 화면 이동시 탭바 숨기기

**Comment by namsoo5** [comment]
``` swift
let vc = SomeView()
vc.hidesBottomBarWhenPushed = true
navigation.push(vc)
```
선언기준을 푸시당하는 뷰컨에 넣어주면
카톡에서처럼 밀리듯이 사라짐
